// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhPs8_Otdhy1z58EhCQ_Y7KEBzg9il0Fo',
    appId: '1:369116543340:web:0d9433759a8283314a9b49',
    messagingSenderId: '369116543340',
    projectId: 'projet-minyar',
    authDomain: 'projet-minyar.firebaseapp.com',
    storageBucket: 'projet-minyar.firebasestorage.app',
    measurementId: 'G-QN54QY8FYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZECHVN5aEuyAWUW59LF3QtpUOYogqY0k',
    appId: '1:369116543340:android:2b540e8b5a3be32e4a9b49',
    messagingSenderId: '369116543340',
    projectId: 'projet-minyar',
    storageBucket: 'projet-minyar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy6BrDcY6oH3605d0pejrRMDt4f2yxi9c',
    appId: '1:369116543340:ios:62f2661b1f48b1c24a9b49',
    messagingSenderId: '369116543340',
    projectId: 'projet-minyar',
    storageBucket: 'projet-minyar.firebasestorage.app',
    iosBundleId: 'com.example.projetMinyar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy6BrDcY6oH3605d0pejrRMDt4f2yxi9c',
    appId: '1:369116543340:ios:62f2661b1f48b1c24a9b49',
    messagingSenderId: '369116543340',
    projectId: 'projet-minyar',
    storageBucket: 'projet-minyar.firebasestorage.app',
    iosBundleId: 'com.example.projetMinyar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhPs8_Otdhy1z58EhCQ_Y7KEBzg9il0Fo',
    appId: '1:369116543340:web:451a2e2237309de44a9b49',
    messagingSenderId: '369116543340',
    projectId: 'projet-minyar',
    authDomain: 'projet-minyar.firebaseapp.com',
    storageBucket: 'projet-minyar.firebasestorage.app',
    measurementId: 'G-QG21SB4JKJ',
  );
}
